import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Votable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Votable</h1>
        <div className={styles.buttonLinkContainer}>
          <Link className={styles.buttonLink} href="/polls">
            <h2>View Polls</h2>
          </Link>
          <Link className={styles.buttonLink} href="/polls/new">
            <h2>New Poll</h2>
          </Link>
        </div>
      </main>
    </>
  )
}
